TYPO3:
  Neos:
    typoScript:
      autoInclude:
        Sfi.YouTube: TRUE
    userInterface:
      translation:
        autoInclude:
          'Sfi.YouTube': ['NodeTypes/*']

Sfi:
  News:
    className: 'YouTube'
    embedParams: 'rel=0&amp;showinfo=0'
