
Sfi:
  YouTube:
    className: YouTube
    embedParams: 'rel=0&amp;showinfo=0'
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Sfi.YouTube:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Sfi.YouTube: true
